apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
type: Opaque
stringData:
  thanos.yaml: |-
    type: s3
    config:
      bucket: thanos
      endpoint: minio.test-shard.svc.cluster.local
      insecure: true
      access_key: ThisIsAVeryLongPasswordForExample
      secret_key: ThisIsAVeryLongPasswordForExample
